export const METADATALOADED = 'METADATALOADED';

export const APPLICATIONSELECTED = 'APPLICATIONSELECTED';

 
export const FUNCTIONSELECTED = 'FUNCTIONSELECTED';

export const APPDIALOGOPEN = 'APPDIALOGOPEN';

export const APPDIALOGCLOSED = 'APPDIALOGCLOSED';

export const FUNCDIALOGOPEN = 'FUNCDIALOGOPEN';

export const FUNCDIALOGCLOSED = 'FUNCDIALOGCLOSED';
