export const APPLICATIONLISTLOADED = 'APPLICATIONLISTLOADED';

export const APPLICATIONSELECTED = 'APPLICATIONSELECTED';

export const APPDIALOGOPEN = 'APPDIALOGOPEN';

export const APPDIALOGCLOSED = 'APPDIALOGCLOSED';
